### ISSUE TITLE
Support for hw bottons.

### ISSUE THREAD

**Issue by Barthy727** [hegocre/ScoreCounter#1]
Hello.

I like your app for wear os. I use it for badminton. However I really miss support for hw buttons. I have Fossil gen 5 and it woud be great if top button woud app point to one player and bottom one for another. 
Do you think its possible to add it? I dont know how to code but ill buy pro version if there will be any with this feature.

Thx for your answer.  :) 

https://developer.android.com/training/wearables/user-input/physical-buttons#kotlin

**Comment by hegocre** [comment]
Hey @Barthy727 

The smartwatch I used had only one button, so that's a feature I hadn't thought about, though it looks like it could be useful and it should not be difficult to implement.

I'll look into it!

**Comment by Barthy727** [comment]
Great! Thank you very much.
I'm open to test it when you implement it!

**Comment by Barthy727** [comment]
Btw.
It would be first app witch does this. I tried every single score counter wear os app on appstore and none have this feature. Some of them have other fancy features but it's not worth it. (at least for me).
Also I was thinking it could be just like in default media player for wear os. There top hw button skip to next track and bottom one to previous. It also works no matter if screen is lock/dimmed or not. :)

**Comment by hegocre** [comment]
Hi!
I tried to implement this, but I'll need some help with testing given that I don't have a Wear OS device with buttons, and android emulator does not have an option to emulate the buttons.
