### ISSUE TITLE
Support Android wear

### ISSUE THREAD

**Issue by xmha97** [hegocre/ScoreCounter#10]
Can I install this app on Android wear?

**Comment by hegocre** [comment]
Hi @xmha97, yes you can! 😄 

You can do it from [Google Play](https://play.google.com/store/apps/details?id=es.hegocre.scorecounter) either on your watch, your computer or your smartphone, or by manually downloading the apk from [releases](https://github.com/hegocre/ScoreCounter/releases/latest) and installing it. Let me know if there is any problem!

Cheers!

**Comment by xmha97** [comment]
Thanks for developing it. 👍🌹
