### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by xmha97** [hegocre/ScoreCounter#5]
Thanks for creatig this app.
Please add support portrait mode.

![Screenshot_2023-02-14-00-56-23-036_es.hegocre.scorecounter.jpg](https://user-images.githubusercontent.com/23485114/218578185-b143535b-c68c-472d-9488-460264e853bc.jpg)

**Comment by hegocre** [comment]
Done! Should be available on Google Play on the next few hours. Thanks for your suggestion!

**Comment by xmha97** [comment]
Thanks
