### ISSUE TITLE
Ability to have more than two scores

### ISSUE THREAD

**Issue by Eschguy** [hegocre/ScoreCounter#8]
Thinking it would be nice to be able to just have scores for 3+ people playing various games, while still keeping a dead-simple UI.

**Comment by hegocre** [comment]
Hi @Eschguy , thank you for your feedback.

I've implemented a new version with multiple scores, it would be nice if you could test it in case you think I missed something. You can download the generated apk from the [actions tab](https://github.com/hegocre/ScoreCounter/actions/runs/4642132992).

Thanks!

**Comment by Eschguy** [comment]
Well done, @hegocre! It works well and is super simple!

My only other idea is maybe allow labels. We did a game of Carcassonne with four people and there was a little struggle with remembering who was which square.

**Comment by hegocre** [comment]
Hello again, @Eschguy 

I'm sorry for not getting back until now, I've been quite busy with projects and work. I've implemented the changes you asked for, you now can assign names to each score. I'll publish the version soon here as well as on Google Play.

Thank you again for your feedback!
